name: sensors_monitoring
description: Service for monitoring sensors. Student project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluent_ui: ^4.7.7
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^13.0.1
  injectable: ^2.3.1
  intl: ^0.18.1
  provider: ^6.0.5
  syncfusion_flutter_charts: ^24.1.44+1
  url_strategy: ^0.2.0
  postgres: 2.6.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
