name: sensors_monitoring
description: Service for monitoring sensors. Student project.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  postgres: ^3.0.7
  fluent_ui: ^4.7.7
  go_router: ^13.0.1
  url_strategy: ^0.2.0
  get_it: ^7.6.4
  injectable: ^2.3.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  uuid: ^4.3.3
  syncfusion_flutter_charts: ^24.1.44+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  freezed: ^2.4.6

flutter:
  uses-material-design: false
